version: '3.2'

services:
  rethinkdb:
    image: "rethinkdb"
    ports:
     - "28015:28015"
     - "18080:8080"
    volumes:
      - type: bind
        source: "${DEV_FOLDER}/db"
        target: /data
  crypto-view-gather:
    environment:
      - PYTHON_APP=./gather/gather.py
    build: .
    volumes:
      - type: bind
        source: "${DEV_FOLDER}"
        target: /code
  crypto-view-api:
    environment:
      - PYTHON_APP=./api/app.py
    build: .
    ports:
     - "5000:5000"
    volumes:
      - type: bind
        source: "${DEV_FOLDER}"
        target: /code
  crypto-view-app:
    image: nginx
    ports: 
      - 8888:80
    volumes:
      - type: bind
        source: "${DEV_FOLDER}/views"
        target: /app
      - type: bind
        source: "${DEV_FOLDER}/views/_docker/nginx.conf"
        target: /etc/nginx/nginx.conf
        read_only: true
  redis:
    image: "redis:alpine"
    ports: 
      - 6379:6379