version: '3.2'


services:
  mongo:
    image: "mongo"
    ports:
     - "27017:27017"
  crypto-view-gather:
    environment:
      - PYTHON_APP=./gather/gather.py
    build: .
    volumes:
      - type: volume
        source: "${DEV_FOLDER}"
        target: /code
  crypto-view-api:
    environment:
      - PYTHON_APP=./api/app.py
    build: .
    ports:
     - "5000:5000"
    volumes:
      - type: volume
        source: "${DEV_FOLDER}"
        target: /code
  crypto-view-app:
    image: nginx
    ports: 
      - 8080:80
    volumes:
      - type: volume
        source: "${DEV_FOLDER}/views"
        target: /app
      - type: volume
        source: "${DEV_FOLDER}/views/_docker/nginx.conf"
        target: /etc/nginx/nginx.conf
        read_only: true
  # redis:
  #   image: "redis:alpine"