version: '3.2'


services:
  ui:
    image: nginx
    ports: 
      - 8080:80
    volumes:
      - type: volume
        source: "${DEV_FOLDER}/ui"
        target: /usr/share/nginx/html
  # rest:
  #   build: .
  #   ports:
  #    - "5000:5000"
  # redis:
  #   image: "redis:alpine"
  mongo:
    image: "mongo"
    ports:
     - "27017:27017"